
#
#
#  GUIType
#  HOPPER , CHEST , LARGE
#
#

GUIType: HOPPER
GUITitle: Menu
TPSlot:
  - 0
  - 1
  - 2
  - 3
Items:
  - BlackPane
  - TPItem1
  - TPItem2
  - TPItem3
  - TPItem4

BlackPane:
  Material: BLACK_STAINED_GLASS_PANE
  Name: " "
  Slots:
    - 4

TPItem1:
  Material: ENDER_EYE
  Name: 現代エリア
  Lore:
    - 現代エリアにTPします
  Glow: true
  Slots:
    - 0

TPItem2:
  Material: ENDER_EYE
  Name: 軍事部エリア
  Lore:
    - 軍事部エリアにTPします
  Glow: true
  Slots:
    - 1

TPItem3:
  Material: ENDER_EYE
  Name: 洋風建築エリア（白樺）
  Lore:
    - 洋風建築エリア（白樺）にTPします
  Glow: true
  Slots:
    - 2

TPItem4:
  Material: ENDER_EYE
  Name: 自由建築エリア
  Lore:
    - 自由建築エリアにTPします
  Glow: true
  Slots:
    - 3

Location:
  0:
    World: world
    X: 0
    Y: 0
    Z: 0
  1:
    World: world
    X: 0
    Y: 0
    Z: 0
  2:
    World: world
    X: 0
    Y: 0
    Z: 0
  3:
    World: world
    X: 0
    Y: 0
    Z: 0