name: BuildServerMenu
version: '${project.version}'
main: info.ahaha.buildservermenu.BuildServerMenu
api-version: 1.17
softdepend: [ Multiverse-Core ]
commands:
  menu:
    description: GUIを表示
  menuconfig:
    description: GUIの表示を設定
    permission: buildservermenu.command.menuconfig
    usage: |
      /<command> ワールド名 name 表示名 - 表示名を設定
      /<command> ワールド名 lore 備考 - 備考を設定
      /<command> ワールド名 reset - 設定をリセット
permissions:
  buildservermenu.command.menuconfig:
    default: op
