name: BuildServerMenu
version: '${project.version}'
main: info.ahaha.buildservermenu.BuildServerMenu
api-version: 1.17
softdepend: [ Multiverse-Core, PrivateWorldPlugin ]
commands:
  menu:
    description: GUIを表示する
  menuconfig:
    description: GUIの表示を設定する
    permission: buildservermenu.command.menuconfig
    usage: |
      /<command> ワールド名 name 表示名 - 表示名を設定
      /<command> ワールド名 reset - 設定をリセット
  menustick:
    description: 右クリックでGUIを表示できる棒を入手する
permissions:
  buildservermenu.command.menuconfig:
    default: op
